version: "2"

services:
    web:
        build: .
        image: flask
        command: /usr/local/bin/gunicorn -w 4 --bind :8080 run_app:app
        ports:
           - "8080:8080"
        volumes: 
            - .:/app
